# Project: ccfText
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = DevC++Text.o Î´ÃüÃû3.o C:/Users/Administrator/Desktop/ccfText.o
LINKOBJ  = DevC++Text.o Î´ÃüÃû3.o C:/Users/Administrator/Desktop/ccfText.o
LIBS     = -L"F:/Program  File(x86)/Dev-Cpp/MinGW64/lib" -L"F:/Program  File(x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/include" -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/include" -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Program  File(x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ccfText.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

DevC++Text.o: DevC++Text.cpp
	$(CPP) -c DevC++Text.cpp -o DevC++Text.o $(CXXFLAGS)

C:/Users/Administrator/Desktop/ccfText.o: C:/Users/Administrator/Desktop/ccfText.cpp
	$(CPP) -c C:/Users/Administrator/Desktop/ccfText.cpp -o C:/Users/Administrator/Desktop/ccfText.o $(CXXFLAGS)
